Expand branding api
everydayhero/experience pull request #40
Opened 2017-03-27 05:57 UTC by HowlingEverett

Standardises the exports of the importable SVGs, pre-compiles them.

Also introduces the `ui-logo` module which is just a component that loads a particular logo and pads it (optionally)

2017-03-27 06:07 UTC, lukebrooker commented
@HowlingEverett Could you add a basic example to Experience Docs > Components? Even if you have a Example.md in `ui-logo` that you import with Experience Docs?

2017-03-28 02:01 UTC, lukebrooker commented
LGTM 👍

2017-03-28 03:16 UTC, benoneal commented
Rounded corners on code blocks, then 👍  when green.

2017-03-28 03:21 UTC, lukebrooker commented
Just needs `navTitle: Logo` in the Frontmatter

2017-03-28 03:22 UTC, lukebrooker requested changes

2017-03-28 03:22 UTC, lukebrooker commented on packages/experience-docs/source/content/components/logo.md
> +path: /components/logo
`navTitle: Logo`

2017-03-28 03:36 UTC, lukebrooker approved these changes

2017-12-19 04:51 UTC, closed without merging